"""empty message

Revision ID: 2bbb83277553
Revises: b10996c090ea
Create Date: 2022-04-17 15:02:19.837230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bbb83277553'
down_revision = 'b10996c090ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbcomp', sa.Column('last_update_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbcomp', 'last_update_date')
    # ### end Alembic commands ###
