"""empty message

Revision ID: 3e489f5cdd77
Revises: 42a7b79d60bb
Create Date: 2022-06-02 15:53:01.681821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e489f5cdd77'
down_revision = '42a7b79d60bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbsppi', sa.Column('next_date_str', sa.String(length=20), nullable=True))
    op.drop_column('dbsppi', 'next_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbsppi', sa.Column('next_date', sa.DATE(), nullable=True))
    op.drop_column('dbsppi', 'next_date_str')
    # ### end Alembic commands ###
