"""empty message

Revision ID: 42a7b79d60bb
Revises: 69a5bdd46af7
Create Date: 2022-06-01 04:49:14.945367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42a7b79d60bb'
down_revision = '69a5bdd46af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbsppi', sa.Column('act_date', sa.Date(), nullable=True))
    op.add_column('dbsppi', sa.Column('cabang', sa.String(length=30), nullable=True))
    op.add_column('dbsppi', sa.Column('next_date', sa.Date(), nullable=True))
    op.add_column('dbsppi', sa.Column('predikat', sa.String(length=20), nullable=True))
    op.add_column('dbsppi', sa.Column('reg', sa.String(length=20), nullable=True))
    op.add_column('dbsppi', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbsppi', 'status')
    op.drop_column('dbsppi', 'reg')
    op.drop_column('dbsppi', 'predikat')
    op.drop_column('dbsppi', 'next_date')
    op.drop_column('dbsppi', 'cabang')
    op.drop_column('dbsppi', 'act_date')
    # ### end Alembic commands ###
