"""empty message

Revision ID: 5b2ff9fbe63d
Revises: 30b1d6526e0e
Create Date: 2022-02-24 16:41:32.297666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b2ff9fbe63d'
down_revision = '30b1d6526e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbcomp', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbcomp', 'status')
    # ### end Alembic commands ###
