"""empty message

Revision ID: 5d82b73bb2e7
Revises: 3e489f5cdd77
Create Date: 2022-06-20 03:51:05.862155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d82b73bb2e7'
down_revision = '3e489f5cdd77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbsppi', sa.Column('next_date', sa.Date(), nullable=True))
    op.drop_column('dbsppi', 'next_date_str')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbsppi', sa.Column('next_date_str', mysql.VARCHAR(length=20), nullable=True))
    op.drop_column('dbsppi', 'next_date')
    # ### end Alembic commands ###
