"""empty message

Revision ID: b10996c090ea
Revises: 5b2ff9fbe63d
Create Date: 2022-03-03 14:49:45.674693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b10996c090ea'
down_revision = '5b2ff9fbe63d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbfucomp', sa.Column('fupic', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbfucomp', 'fupic')
    # ### end Alembic commands ###
