"""empty message

Revision ID: 0197bd013c7a
Revises: c442f9f45ce7
Create Date: 2025-11-19 22:11:38.546807

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0197bd013c7a'
down_revision = 'c442f9f45ce7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_nota', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Uuid(), nullable=False))
        batch_op.drop_constraint(batch_op.f('tbl_nota_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'all_user', ['user_id'], ['id'])
        batch_op.drop_column('user_new_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_nota', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_new_id', mysql.CHAR(length=32), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tbl_nota_ibfk_1'), 'all_user', ['user_new_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
