"""empty message

Revision ID: 6127886eb774
Revises: d228b6cdde23
Create Date: 2025-11-25 16:26:42.072650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6127886eb774'
down_revision = 'd228b6cdde23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
