"""empty message

Revision ID: 8a0f612147d7
Revises: 
Create Date: 2025-11-17 23:21:00.829266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a0f612147d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.Text(), nullable=False),
    sa.Column('password', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('db_comp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_agr', sa.String(length=20), nullable=False),
    sa.Column('nama', sa.String(length=20), nullable=False),
    sa.Column('area_cg', sa.String(length=20), nullable=False),
    sa.Column('cg_name', sa.String(length=20), nullable=False),
    sa.Column('class_comp', sa.String(length=20), nullable=False),
    sa.Column('agent_notes', sa.Text(), nullable=False),
    sa.Column('input_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_update_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_agr')
    )
    op.create_table('db_fu_comp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idcomp', sa.Integer(), nullable=False),
    sa.Column('fupic', sa.String(length=25), nullable=False),
    sa.Column('fudate', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('db_sppi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nip', sa.String(length=10), nullable=False),
    sa.Column('nama', sa.String(length=30), nullable=False),
    sa.Column('reg', sa.String(length=20), nullable=False),
    sa.Column('cabang', sa.String(length=30), nullable=False),
    sa.Column('jabatan', sa.String(length=20), nullable=False),
    sa.Column('predikat', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('act_date', sa.Date(), nullable=False),
    sa.Column('next_date', sa.Date(), nullable=False),
    sa.Column('exp_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_beli',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('penulis_beli', sa.Text(), nullable=False),
    sa.Column('judul_beli', sa.Text(), nullable=False),
    sa.Column('tanggal_buat', sa.Date(), nullable=False),
    sa.Column('tahun_beli', sa.Integer(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('no_beli', sa.Text(), nullable=False),
    sa.Column('linkbeli', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_bersama',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('penulis', sa.Text(), nullable=False),
    sa.Column('judul', sa.Text(), nullable=False),
    sa.Column('tanggal_buat', sa.Date(), nullable=False),
    sa.Column('tahun', sa.Integer(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('no_bersama', sa.Text(), nullable=False),
    sa.Column('link', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_memo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('penulis_memo', sa.Text(), nullable=False),
    sa.Column('judul_memo', sa.Text(), nullable=False),
    sa.Column('tanggal_buat', sa.Date(), nullable=False),
    sa.Column('tahun_memo', sa.Integer(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('no_memo', sa.Text(), nullable=False),
    sa.Column('linkmemo', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tbl_nota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('penulis_nota', sa.Text(), nullable=False),
    sa.Column('judul_nota', sa.Text(), nullable=False),
    sa.Column('tanggal_buat', sa.Date(), nullable=False),
    sa.Column('tahun_nota', sa.Integer(), nullable=False),
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('no_nota', sa.Text(), nullable=False),
    sa.Column('linknota', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tbl_nota')
    op.drop_table('tbl_memo')
    op.drop_table('tbl_bersama')
    op.drop_table('tbl_beli')
    op.drop_table('db_sppi')
    op.drop_table('db_fu_comp')
    op.drop_table('db_comp')
    op.drop_table('all_user')
    # ### end Alembic commands ###
