"""empty message

Revision ID: d228b6cdde23
Revises: 0197bd013c7a
Create Date: 2025-11-19 22:23:15.618798

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd228b6cdde23'
down_revision = '0197bd013c7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_beli', schema=None) as batch_op:
        batch_op.drop_column('penulis_beli')

    with op.batch_alter_table('tbl_bersama', schema=None) as batch_op:
        batch_op.drop_column('penulis')

    with op.batch_alter_table('tbl_memo', schema=None) as batch_op:
        batch_op.drop_column('penulis_memo')

    with op.batch_alter_table('tbl_nota', schema=None) as batch_op:
        batch_op.drop_column('penulis_nota')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_nota', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penulis_nota', mysql.TEXT(), nullable=False))

    with op.batch_alter_table('tbl_memo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penulis_memo', mysql.TEXT(), nullable=False))

    with op.batch_alter_table('tbl_bersama', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penulis', mysql.TEXT(), nullable=False))

    with op.batch_alter_table('tbl_beli', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penulis_beli', mysql.TEXT(), nullable=False))

    # ### end Alembic commands ###
