"""empty message

Revision ID: f44ee96356f4
Revises: 6127886eb774
Create Date: 2025-11-26 13:29:49.247935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f44ee96356f4'
down_revision = '6127886eb774'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('all_user', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
